<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerN7a82xA\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerN7a82xA/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerN7a82xA.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerN7a82xA\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerN7a82xA\App_KernelDevDebugContainer([
    'container.build_hash' => 'N7a82xA',
    'container.build_id' => 'cc613842',
    'container.build_time' => 1582235553,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerN7a82xA');
